apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: gcp-template
  title: Google Cloud Platform infrastructure template
  description: Create a simple GCP stack
  tags:
    - gcp
    - gke
spec:
  owner: diego.braga86@gmail.com
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - component_id
      - description
      - nodes_count 
      - nodes_size 
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Help others understand what this service does.
      nodes_count:
        title: Number of nodes of the GKE cluster
        type: integer
        description: Number of nodes of the GKE cluster 
      nodes_size:
        title: Size of nodes of the GKE cluster 
        type: integer
        default: 3
        description: Size of nodes of the GKE cluster
